# application.yml
spring:
  security:
    jwt:
      key: abcdefghijk
      expire: 7
  datasource:
    url: jdbc:mysql://localhost:3306/WebsiteDB?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234
  data:
    redis:
      host: localhost
      port: 6379